!!python/object:parameters.Parameters
batch_size: 16
config_name: /syntax/configs/config_fine_tuning_languages_ru_3000_4000_estep100.yaml
cutoff_len: 1500
dataset_config: !!python/object:config.DatasetConfig
  conll_test_file_path: /syntax/syntax_finetuning_data/conllu/UD_Russian-SynTagRus/ru_syntagrus-ud-test.conllu
  dev_file_path: /syntax/syntax_finetuning_data/dataset_simple_rel/UD_Russian-SynTagRus/ru_simple_syntagrus_grct_dev.json
  test_file_path: /syntax/syntax_finetuning_data/dataset_simple_rel/UD_Russian-SynTagRus/ru_simple_syntagrus_grct_test.json
  train_file_path: /syntax/syntax_finetuning_data/dataset_simple_rel/UD_Russian-SynTagRus/ru_simple_syntagrus_grct_train.json
  treebank: ru_syntagrus_grct
  treebank_repr: grct
epochs: 3
eval_steps: 100
experiment_number: 2
group_by_length: false
init_lora_weights: loftq
learning_rate: 0.0003
lora_alpha: 16
lora_dropout: 0.05
lora_r: 8
micro_batch_size: 2
model_config: !!python/object:config.ModelConfig
  is_instruct: false
  model_name: Qwen/Qwen3-4B-Base
  per_device_eval_batch_size: 2
  torch_empty_cache_steps: 2
model_parameters:
  model_name: Qwen/Qwen3-4B-Base
output_experiment_path: /syntax/adapters/ft_languages_ru/Qwen3_4B_Base_ru_syntagrus_grct/2
output_model_dataset_path: /syntax/adapters/ft_languages_ru/Qwen3_4B_Base_ru_syntagrus_grct
root_output_dir_path: /syntax/adapters/ft_languages_ru
save_epoch_adapters: true
save_steps: 50
seed: 3000
treebank_parameters:
  treebank_name: ru_syntagrus_grct
