!!python/object:parameters.Parameters
batch_size: 16
config_name: /syntax_finetuning/src/configs/config_qwen8_bots.yaml
dataset_config: !!python/object:config.DatasetConfig
  dev_file_path: /syntax_finetuning/src/data/syntagrus/grct_ru_syntagrus-dev.json
  train_file_path: /syntax_finetuning/src/data/syntagrus/grct_ru_syntagrus-train.json
  treebank: syntagrus_grct
disable_qlora: false
epochs: 3
experiment_number: 0
group_by_length: false
learning_rate: 0.0003
lora_alpha: 16
lora_dropout: 0.05
lora_r: 8
micro_batch_size: 8
model_config: !!python/object:config.ModelConfig
  is_instruct: false
  model_name: /models8/Qwen3-8B-Base
root_output_dir_path: /adapters
treebank: syntagrus
